database:
  type: sqlite
  sqlite_path: accounts.db
  postgres_url: postgresql://user:pass@localhost:5432/massreg

proxy:
  enabled: true
  mode: static  # Если есть rotation_url от getproxy.pro, замените на 'rotation'
  type: http
  dead_timeout: 300
  strategy: round-robin
  proxies:
    # ЗАМЕНЕН НА АКТУАЛЬНЫЙ ПРОКСИ 
    - "92.204.171.83:9000:a995a71bbb0ee8097afe633a914168e5-type-residential-country-CR:59c8d77e-4957-4af2-9058-3cac156a4e2e"
    - "92.204.171.83:9000:a995a71bbb0ee8097afe633a914168e5-type-residential-country-AD:59c8d77e-4957-4af2-9058-3cac156a4e2e"
    - "92.204.171.83:9000:a995a71bbb0ee8097afe633a914168e5-type-residential-country-BE:59c8d77e-4957-4af2-9058-3cac156a4e2e"
    - "51.81.149.81:5001:gpilxiik60-residential-AF:Gjzgv4EQ07"
    # Рекомендую: Добавить сюда минимум 3-5 разных прокси, чтобы round-robin реально менял IP

sms:
  api_key: M1ndLabrTT_2
  api_url: https://46.21.159.86/stubs/handler_api.php
  partner_url: https://46.21.159.86/partner
  service: Microsoft
  country: all
  max_price: 0
  max_sms_wait: 300
  services:
    - Microsoft

worker:
  threads: 20
  total_registrations: 100
  headless: true
  retry_count: 3
  number_retries: 3  # Сколько раз менять номер+прокси при неудаче

ml:
  model_path: ml_model.json
  learning_rate: 0.15
  l2: 0.01
  min_samples: 10